# BloatVeil Configuration File

# Core Function
hide_mode=MB
mb_umount_bind=true

# Brick Rescue
brick_rescue=true
brick_timeout=120
brick_and_disable=true
last_worked_target_list=true

# Target List optimization
auto_update_target_list=true
